name: int_news
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.7
  get_it: ^9.0.5
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/splash/
